### ISSUE TITLE
No support for fragmented response

### ISSUE THREAD

**Issue by Fedcomp** [gries/rcon#1]
I'm running Rust server, and trying to receive response of host variables.
Basically i authenticate, send 'find host', in result i get only first string of response, rcon library ignores next packets. Spent some time to figure it out. Wireshark clearly show i server sent next message of rcon answer but rcon library ignores it.

There's no way i can "ask" rcon library to get next response as well.

**Comment by gries** [comment]
Hi thank you for the feedback,
currently fragmented responses are not supported but I'll try to add them soon. (Hopefully over the weekend)

**Comment by gries** [comment]
Hi, the fragmented responses are supported now.
However I have just tested this on a minecraft server so if you still have any troubles with your Rust server please reopen this issue :)
